### ISSUE TITLE
image-captioning-gan

### ISSUE THREAD

**Issue by tom285** [pratyushmore/lunch-tag-bot#1]
Sorry for the inconvenience
I am a student from Taiwan.
Thank you for the python code(image-captioning-gan) you provided in the past
(https://github.com/ctsy9349/image-captioning-gan)
This has a lot of learning gains for me.
Sorry for the inconvenience.
I have some questions.
Is there a detailed description of how to use this model and its model schema description?
Is there more relevant papers that can be referenced to help understand this model?
Thank you for the time and patience you devoted to reading my messages.
I really appreciate that.

**Comment by pratyushmore** [comment]
Hi @tom285, thanks for your message. Unfortunately, I am not supporting that project anymore. Feel free to go through the code to figure it out. It would take me a while to document the entire usage. Which is why I decided to make the repo private.

If you have any specific small questions, though, I can try to answer them (although I cannot guarantee within how much time).

Closing this issue, as it is unrelated to this project.

Most of the runners follow similar commands to: https://github.com/yunjey/show-attend-and-tell
